zuul:
  routes:
    payment-server:
      path: /pay/**
    order-server:
      path: /order/**
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
ribbon:
  ReadTimeout:  10000
  ConnectTimeout: 10000